In [1]:
import pandas as pd

In [2]:
file_path = "Libraries.csv"

# Read the mouse data and the study results
library_data = pd.read_csv(file_path)
library_data.head()

/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (2,17,18,19,20,21,22,23,24,25,26,27,28,29,30,34,35,36,37,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,State,Library ID,Submission Year,Library Name,Street Address,City,Zip Code,Longitude,Latitude,State Code,...,Children's Programs,Young Adult Programs,Library Program Audience,Children's Program Audience,Young Adult Program Audience,Public Internet Computers,Internet Computer Use,Wireless Internet Sessions,Start Date,End Date
0,AK,AK0001,2015,ANCHOR POINT PUBLIC LIBRARY,72551 MILO FRITZ AVENUE,ANCHOR POINT,99556,-151.840007,59.779604,2,...,15,0,146,128,0,8,1675,0,7/1/2013,6/30/2014
1,AK,AK0002,2015,ANCHORAGE PUBLIC LIBRARY,3600 DENALI STREET,ANCHORAGE,99503,-149.876781,61.187677,2,...,906,412,68778,41259,9656,135,138689,0,1/1/2013,12/31/2013
2,AK,AK0003,2015,ANDERSON VILLAGE LIBRARY,101 FIRST STREET,ANDERSON,99744,-149.178635,64.343598,2,...,7,0,16,16,0,4,480,0,7/1/2013,6/30/2014
3,AK,AK0006,2015,KUSKOKWIM CONSORTIUM LIBRARY,420 CHIEF EDDIE HOFFMAN HIGHWAY,BETHEL,99559,-161.802957,60.785755,2,...,37,1,815,417,15,9,20000,0,7/1/2013,6/30/2014
4,AK,AK0007,2015,BIG LAKE PUBLIC LIBRARY,3140 SOUTH BIG LAKE ROAD,BIG LAKE,99652,-149.818403,61.546612,2,...,118,11,6316,3893,1396,22,11301,5148,7/1/2013,6/30/2014

In [3]:
library_data.columns

Index(['State', 'Library ID', 'Submission Year', 'Library Name',
       'Street Address', 'City', 'Zip Code', 'Longitude', 'Latitude',
       'State Code', 'County Code', 'County', 'County Population',
       'Public Library Definition', 'Legal Basis', 'Administrative Structure',
       'Interlibrary Relationship', 'Service Population',
       'Service Population Without Duplicates', 'Central Libraries',
       'Branch Libraries', 'Bookmobiles', 'MLS Librarians', 'Librarians',
       'Employees', 'Total_Staff', 'Local_Government_Operating_Revenue',
       'State_Government_Operating_Revenue',
       'Federal_Government_Operating_Revenue', 'Other_Operating_Revenue',
       'Total_Operating_Revenue', 'Salaries', 'Benefits',
       'Total_Staff_Expenditures', 'Print_Collection_Expenditures',
       'Digital_Collection_Expenditures', 'Other Collection Expenditures',
       'Total Collection Expenditures', 'Other Operating Expenditures',
       'Total Operating Expenditures', 'Local Government Capital Revenue',
       'State Government Capital Revenue',
       'Federal Government Capital Revenue', 'Other Capital Revenue',
       'Total Capital Revenue', 'Total Capital Expenditures',
       'Print Collection', 'Digital Collection', 'Audio Collection',
       'Downloadable Audio', 'Physical Video', 'Downloadable Video',
       'Local Cooperative Agreements', 'State Licensed Databases',
       'Total Licensed Databases', 'Print Subscriptions', 'Hours Open',
       'Library Visits', 'Reference Transactions', 'Registered Users',
       'Circulation Transactions', 'Interlibrary Loans Provided',
       'Interlibrary Loans Received', 'Library Programs',
       'Children's Programs', 'Young Adult Programs',
       'Library Program Audience', 'Children's Program Audience',
       'Young Adult Program Audience', 'Public Internet Computers',
       'Internet Computer Use', 'Wireless Internet Sessions', 'Start Date',
       'End Date'],
      dtype='object')

In [4]:
library_df= library_data[["State", 'Library ID', 'Submission Year', 'Library Name',
       'Street Address', 'City', 'Zip Code', 'Longitude', 'Latitude',
       'State Code', 'County Code', 'County', 'County Population',"Print_Collection_Expenditures",
       'Digital_Collection_Expenditures', 'Total Collection Expenditures','Total Operating Expenditures', 'Print Collection', 'Digital Collection', 'Audio Collection','Library Visits',
        'Registered Users']]
library_df

,State,Library ID,Submission Year,Library Name,Street Address,City,Zip Code,Longitude,Latitude,State Code,...,County Population,Print_Collection_Expenditures,Digital_Collection_Expenditures,Total Collection Expenditures,Total Operating Expenditures,Print Collection,Digital Collection,Audio Collection,Library Visits,Registered Users
0,AK,AK0001,2015,ANCHOR POINT PUBLIC LIBRARY,72551 MILO FRITZ AVENUE,ANCHOR POINT,99556,-151.840007,59.779604,2,...,57477,3021,0,4030,21282,16843,0,258,5379,396
1,AK,AK0002,2015,ANCHORAGE PUBLIC LIBRARY,3600 DENALI STREET,ANCHORAGE,99503,-149.876781,61.187677,2,...,301010,700747,198422,1152280,10910542,481861,9773,28552,942873,119619
2,AK,AK0003,2015,ANDERSON VILLAGE LIBRARY,101 FIRST STREET,ANDERSON,99744,-149.178635,64.343598,2,...,1921,2206,425,3508,11449,15304,0,48,874,161
3,AK,AK0006,2015,KUSKOKWIM CONSORTIUM LIBRARY,420 CHIEF EDDIE HOFFMAN HIGHWAY,BETHEL,99559,-161.802957,60.785755,2,...,17868,8295,1635,14801,261212,34115,165,434,44980,1500
4,AK,AK0007,2015,BIG LAKE PUBLIC LIBRARY,3140 SOUTH BIG LAKE ROAD,BIG LAKE,99652,-149.818403,61.546612,2,...,97882,21552,0,21552,347675,23810,9773,1813,43285,3878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9237,WY,WY0019,2015,SUBLETTE COUNTY LIBRARY,155 S TYLER ST,PINEDALE,82941,-109.861281,42.865097,56,...,10057,63000,10000,112968,1242920,73390,7766,4480,197314,6073
9238,WY,WY0020,2015,TETON COUNTY LIBRARY,125 VIRGINIAN LANE,JACKSON,83001,-110.779203,43.471780,56,...,22930,68824,30297,130105,3159627,81207,7832,12488,280211,32446
9239,WY,WY0021,2015,UINTA COUNTY LIBRARY,701 MAIN ST,EVANSTON,82930,-110.963405,41.265975,56,...,20904,0,0,0,685960,111377,7087,5916,112403,16279
9240,WY,WY0022,2015,WASHAKIE COUNTY LIBRARY,1019 COBURN AVE,WORLAND,82401,-107.955461,44.015771,56,...,8322,16000,0,25317,247071,73464,7087,2065,73300,6774
9241,WY,WY0023,2015,WESTON COUNTY LIBRARY SYSTEM,23 WEST MAIN ST,NEWCASTLE,82701,-104.202302,43.855671,56,...,7201,10671,1138,16443,308016,43264,7087,1862,43103,4929

In [5]:
library_df.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9242 entries, 0 to 9241
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   State                            9242 non-null   object
 1   Library ID                       9242 non-null   object
 2   Submission Year                  9242 non-null   object
 3   Library Name                     9242 non-null   object
 4   Street Address                   9242 non-null   object
 5   City                             9242 non-null   object
 6   Zip Code                         9242 non-null   int64
 7   Longitude                        9242 non-null   float64
 8   Latitude                         9242 non-null   float64
 9   State Code                       9242 non-null   int64
 10  County Code                      9242 non-null   int64
 11  County                           9242 non-null   object
 12  County Population                9242 non-null   int64
 13  Print_Collection_Expenditures    9242 non-null   object
 14  Digital_Collection_Expenditures  9242 non-null   object
 15  Total Collection Expenditures    9242 non-null   object
 16  Total Operating Expenditures     9242 non-null   object
 17  Print Collection                 9242 non-null   object
 18  Digital Collection               9242 non-null   object
 19  Audio Collection                 9242 non-null   object
 20  Library Visits                   9242 non-null   object
 21  Registered Users                 9242 non-null   object
dtypes: float64(2), int64(4), object(16)
memory usage: 1.6+ MB

In [6]:
mask= library_df["Print_Collection_Expenditures"] !="H_14"
library_df= library_df.loc[mask]

In [7]:
#convert columns to floats

columns= ["Print_Collection_Expenditures",'Digital_Collection_Expenditures',
       'Total Collection Expenditures','Total Operating Expenditures', 'Print Collection', 'Digital Collection', 'Audio Collection','Library Visits',
        'Registered Users']

for col in columns:
    library_df[col] = library_df[col].astype(float)
    print(col)
library_df.info()

Print_Collection_Expenditures
Digital_Collection_Expenditures
Total Collection Expenditures
Total Operating Expenditures
Print Collection
Digital Collection
Audio Collection
Library Visits
Registered Users
<class 'pandas.core.frame.DataFrame'>
Int64Index: 9241 entries, 0 to 9241
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   State                            9241 non-null   object
 1   Library ID                       9241 non-null   object
 2   Submission Year                  9241 non-null   object
 3   Library Name                     9241 non-null   object
 4   Street Address                   9241 non-null   object
 5   City                             9241 non-null   object
 6   Zip Code                         9241 non-null   int64
 7   Longitude                        9241 non-null   float64
 8   Latitude                         9241 non-null   float64
 9   State Code                       9241 non-null   int64
 10  County Code                      9241 non-null   int64
 11  County                           9241 non-null   object
 12  County Population                9241 non-null   int64
 13  Print_Collection_Expenditures    9241 non-null   float64
 14  Digital_Collection_Expenditures  9241 non-null   float64
 15  Total Collection Expenditures    9241 non-null   float64
 16  Total Operating Expenditures     9241 non-null   float64
 17  Print Collection                 9241 non-null   float64
 18  Digital Collection               9241 non-null   float64
 19  Audio Collection                 9241 non-null   float64
 20  Library Visits                   9241 non-null   float64
 21  Registered Users                 9241 non-null   float64
dtypes: float64(11), int64(4), object(7)
memory usage: 1.6+ MB

/var/folders/93/69nrl93d0k36xslv9kn84gcc0000gn/T/ipykernel_34800/1460722048.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  library_df[col] = library_df[col].astype(float)

In [8]:
#Save as a csv
library_df.to_csv("library_df.csv", encoding="utf-8", index=False)